### ISSUE TITLE
LDAP aithentication

### ISSUE THREAD

**Issue by cyberb** [pi-hole/AdminLTE#1002]
I would like to add a minimal LDAP authentication feature as I am trying to include pihole as an app for syncloud.org project.

I have few questions:
1. Will you accept such a feature?
2. Is this project will be replaced by https://github.com/pi-hole/web or not?

Thank you

**Comment by Mcat12** [comment]
This web interface will be replaced by the one you mentioned (plus the new API). This feature should be implemented there instead of in this repo.

However, I am still waiting on more buy-in from the rest of the team before we can release the new web interface. Until that is achieved, the new web interface won't be released.

**Comment by cyberb** [comment]
In the new api what code do you use on backend side, is it still php?

**Comment by Mcat12** [comment]
The API is in Rust: https://github.com/pi-hole/api

See this PR for more details on how to install it: https://github.com/pi-hole/pi-hole/pull/2692

**Comment by cyberb** [comment]
https://github.com/pi-hole/api/issues/232
