### ISSUE TITLE
Update checks inconsistent?

### ISSUE THREAD

**Issue by TwizzyDizzy** [pi-hole/AdminLTE#1030]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Web interface shows `(Update available!)`

![image](https://user-images.githubusercontent.com/179595/67093180-57706580-f1b1-11e9-90d8-d2aae8834ea1.png)

I would expect `/usr/local/bin/pihole -up -checkOnly` to show the same.

**Actual behaviour:**

```
root@pi:~# /usr/local/bin/pihole -up -checkOnly
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		up to date

  [✓] Everything is up to date!
```

**Steps to reproduce:**

No idea how to reproduce this.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):** https://tricorder.pi-hole.net/

`i89tfzthgm`

**Troubleshooting undertaken, and/or other relevant information:**

No idea how to troubleshoot this, sorry.

**Comment by PromoFaux** [comment]
Reload the cache on the browser (`ctrl + F5`), or wait some time and it will (should!) update the value automatically.

**Comment by TwizzyDizzy** [comment]
Hi @PromoFaux 

that was fast :) Reloading with disabled cache (developer console AND `ctrl+shift+r`) does not change anything.

Waiting doesn't seem to be an option either, I presume, as `4.3.2` has been on Sep 15, which was a month ago.

Cheers
Thomas

**Comment by PromoFaux** [comment]
Oh hold up.. I've just now looked at your debug token, you're actually still on 4.3.1, so the web interface is correct.

I'm trying to remember what `pihole update --check-only` actually does behind the scenes (it's been a while)

What do you get if you just run `pihole -up`, does it kick off the update process?

```
*** [ DIAGNOSING ]: Core version
[i] Core: v4.3.1 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Branch: master
[i] Commit: v4.3.1-40-ge41c4b5
```

**Comment by TwizzyDizzy** [comment]
Here's the output of `pihole -up`

```
root@pi:~# pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		up to date

  [✓] Everything is up to date!
```

**Comment by DL6ER** [comment]
Note that the web interface sources the version from a (frequently updated) file instead of querying the repositories directly. This is done to prevent a notable delay of 1-3 seconds due to the `git` calls on every page load. This version cache might be out of date for you.

How do this files referenced here look like for you?
https://github.com/pi-hole/pi-hole/blob/e41c4b5bb691cea1f5b950d39518d8c404b5846e/advanced/Scripts/updatecheck.sh#L50
https://github.com/pi-hole/pi-hole/blob/e41c4b5bb691cea1f5b950d39518d8c404b5846e/advanced/Scripts/updatecheck.sh#L78

**Comment by TwizzyDizzy** [comment]
Hi @DL6ER 

```
root@pi:~# cat /etc/pihole/GitHubVersions
v4.3.2 v4.3.2 v4.3.1
```

```
root@pi:~# cat /etc/pihole/localversions
v4.3.1-40-ge41c4b5 v4.3.2-0-g38d8e77 v4.3.1
```

**Comment by DL6ER** [comment]
Okay, so that's interesting. How about
```
cat /etc/pihole/localbranches
```

**Comment by TwizzyDizzy** [comment]
```
root@pi:~# cat /etc/pihole/localbranches
master master master
```

**Comment by DL6ER** [comment]
```
v4.3.1-40-ge41c4b5
```
from your `/etc/pihole/localversions` means you are on some intermediate commit on pi-hole core?

Please run
```
cd /etc/.pihole
git pull
```

**Comment by TwizzyDizzy** [comment]
Just did exactly what you said, see this log: [repair.log](https://github.com/pi-hole/AdminLTE/files/3744431/repair.log)

**Comment by DL6ER** [comment]
Hmm, it shows again
> v4.3.1-40-ge41c4b5

for the core version
 The commit is correct (https://github.com/pi-hole/pi-hole/commit/e41c4b5bb691cea1f5b950d39518d8c404b5846e) for [`v4.3.2`](https://github.com/pi-hole/pi-hole/releases/tag/v4.3.2), however, it does not show up as a tagged commit.

Maybe `sudo git fetch --tags --force` in `/etc/.pihole` can help with this.

Saying all this because it is odd what your Pi-hole displays. It is unclear if this is causing the issue you reported here as I'm unable to reproduce this at this time.

**Comment by TwizzyDizzy** [comment]
Just did the force-fetch, and indeed the 4.3.2 tag seems to have been updated (` t [tag update]      v4.3.2     -> v4.3.2`).

Did a repair again after the, full output: [force-fetch+repair.log](https://github.com/pi-hole/AdminLTE/files/3744538/force-fetch%2Brepair.log)

And now, indeed, I seem to have gotten the latest version (probably rather the fetch than the repair, that achieved this):

```
root@pi:/etc/.pihole# pihole -v
  Pi-hole version is v4.3.2 (Latest: v4.3.2)
  AdminLTE version is v4.3.2 (Latest: v4.3.2)
  FTL version is v4.3.1 (Latest: v4.3.1)
```

Web frontend doesn't show a warning anymore:

![image](https://user-images.githubusercontent.com/179595/67106067-38320200-f1ca-11e9-84bc-c321d2727ba7.png)

The only half-reasonable explanation I have for this is, that the tag has been modified after I first installed pihole? Does that make sense?

Cheers
Thomas

**Comment by DL6ER** [comment]
> EDIT: pihole updatechecker local produces no output.

This is expected. It is a command that is run periodically by `cron` and actually not meant for direct user interaction. It outputs only on error.

> The only half-reasonable explanation I have for this is, that the tag has been modified after I first installed pihole? Does that make sense?

No. The reason is very likely that you updated *before* the tag was available. Due to certain GitHub-caused restrictions in our release workflow, we first have to merge to `master` (create the commit) *before* we can (manually!) attach the tag to this commit. As we make sure that nothing went wrong with the `master` merge before we tag the release, there might be a delay of 2-3 minutes which is a window you probably have hit just by chance.

**Comment by TwizzyDizzy** [comment]
Well then... looks like I have been quite lucky ;)

But thanks for walking me through this, it is very much appreciated!

Before closing this issue: is this something the update check _should_ have been detecting? It's pretty much an edge case, so it might not be worth catching that condition.

**Comment by DL6ER** [comment]
> It's pretty much an edge case, so it might not be worth catching that condition.

The code should also work in edge cases. I will look at this (probably next weekend if nobody beats me to it).
You can leave the issue ticket open, it should be auto-closed when we release v5.0 (which will then contain said fix).

**Comment by TwizzyDizzy** [comment]
Addition: if you like, I can also restore the repository `/etc/.pihole` from backup (and send you a link) from before the force-fetching fixed it. Maybe that helps debugging?

Cheers
Thomas

**Comment by DL6ER** [comment]
Thanks, but I don't think it'll be necessary. I should be able to reproduce this locally by just untagging the respective commit in my repository.

**Comment by PromoFaux** [comment]
@yubiuser has correctly pointed out that we update based on tags, these days, rather than commits - so this should no longer be an issue. We can re-visit if it turns out that this is still an issue

**Comment by yubiuser** [comment]
For reference: https://github.com/pi-hole/pi-hole/pull/4475
