### ISSUE TITLE
Add /etc/hosts to Teleporter 

### ISSUE THREAD

**Issue by msberends** [pi-hole/AdminLTE#1105]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

I would add the `etc/hosts` file to the Teleporter as well, since users use it to add IP addresses so they show up in the web interface as human-readable client names. Restoring the file is another thing, but for backup this is IMHO very important. I would lose 20 manually set entries if my RPi crashes.

So please add `archive_add_file("/etc/hosts","hosts");` to:

https://github.com/pi-hole/AdminLTE/blob/de7aa5a3fafb7d82b50d9972a1451a848c89037a/scripts/pi-hole/php/teleporter.php#L179-L185

In the web interface, you could mention that the file contains the hosts, but restoring should be followed by `pihole restartdns` or so.

**Comment by DL6ER** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net), as mentioned in our [Issue Templates](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md).

As this is a really minor idea and I can see why you have this request, I will likely just add it. However, note that importing/restoring will NOT be possible for two reasons:
1. We *should* not do it, because - how would you resolve conflicts? Overwriting `/etc/hosts` with a file maybe coming from another machine sound really bad.
2. We *cannot* do it. The restoring happens from the web interface. Nothing in the process is `root` at any point. Hence, we cannot write to this file. This is a security measure we're not going to soften.

**Comment by msberends** [comment]
Fair enough, thank you very much!

**Comment by msberends** [comment]
Merged, can be closed. Thanks again!
