### ISSUE TITLE
Webinterface 4.3.3 showing 4.3.2

### ISSUE THREAD

**Issue by NeverEatYellowSwissSnow** [pi-hole/AdminLTE#1167]
After updating from webinterface v4.3.2 to v4.3.3 it's still showing v4.3.2 and mentioning to update when opening the webinterface, even after system reboot. But command "pihole -v" gives webinterface 4.3.3, so this is correct.
Using Ubuntu server 18.04 with Pi-hole v4.3.2

**Comment by PromoFaux** [comment]
The versions shown in the web interface are populated from a file that is updated periodically, though off the top of my head I do not remember how often this is (@DL6ER may be able to shine some light on that)

Though, side note, I wonder if we should force the update of this file after a successful run of `pihole -up`

**Comment by dschaper** [comment]
It's in the browser cache, just need to clear the cache or restart the browser.

**Comment by PromoFaux** [comment]
Found it. 

The local versions are checked by a `cron` job every 10 mins:

```
# Pi-hole: Grab local version and branch every 10 minutes
*/10 *  * * *   root    PATH="$PATH:/usr/local/bin/" pihole updatechecker local
```

you can manually force the version refresh by running `pihole updatechecker local`, and also try to refresh your browser cache if that does not work

**Comment by PromoFaux** [comment]
Hopefully this is addressed in future versions by https://github.com/pi-hole/pi-hole/pull/3147

**Comment by beerisgood** [comment]
> 
> you can manually force the version refresh by running `pihole updatechecker local`, and also try to refresh your browser cache if that does not work

This command fix the problem for me.

**Comment by PromoFaux** [comment]
Great stuff, thanks for reporting back

**Comment by Mattyfaz** [comment]
Thanks @PromoFaux, `pihole updatechecker local` fixed it for me.

**Comment by zorich51** [comment]
After updating pihole it shows "Web Interface Version 4.3.2 (Update available)"when opening the web interface.

Checking on the console pihole -v shows
  Pi-hole version is v4.4 (Latest: v4.4)
  AdminLTE version is v4.3.2 (Latest: v4.3.3)
  FTL version is v4.3.1 (Latest: v4.3.1)

I tried to update several times since then. The result is always the same:
xxx:~ $ pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
fatal: The remote end hung up unexpectedly
  [i] Web Interface:	up to date
  [i] FTL:		up to date

Do you have any idea what's causing this?

I am running pihole on
  Distributor ID:	Raspbian
  Description:		Raspbian GNU/Linux 9.11 (stretch)
  Release:		9.11
  Codename:		stretch
with kernel version
  4.19.66-v7+

**Comment by PromoFaux** [comment]
> fatal: The remote end hung up unexpectedly

This looks to be a separate issue to the one reported in the OP. At a guess you're having internet issues... Please open a new issue thread and provide a debug token, thanks!

**Comment by zorich51** [comment]
New issue #1175 created!

Immediately before trying to update pihole I updated my Raspbian installation and did not experience any Internet issues. All my other active devices in the LAN have Internet access. So it seems highly unlikely that this is an Internet issue on my end.

**Comment by yubiuser** [comment]
Version 4.3.3 is gone for a long time now.
