### ISSUE TITLE
Bar graphs have different width in v5.0 due to missing zero allocation to intervals without queries

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/AdminLTE#1211]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**
3
---
**Expected behaviour:**

Bar graphs in v5.0 should have the same width everywhere and intervals with 0 queries should be zero.

**Actual behaviour:**

No intervals exists with zero queries and bar graphs neighboring such intervals are wider than others.

**Steps to reproduce:**

Select a time period in the long term data -> graphics (but I have seen it in the dashboard as well) where you know some time (eg night) will have zero/a few queries and some time will have a lot of queries. Bars have different width.

**Troubleshooting undertaken, and/or other relevant information:**

I have tracked it down to the following function that claims to fill intervals with no queries with zeros but it doesn't. I used git blame and saw that there was once an actual allocation of somethin like "set data.row=0" but it got lost somehow.

https://github.com/pi-hole/AdminLTE/blob/8e51f754e4ad2fa37d3e688935914223fa68db1c/api_db.php#L368

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/add-more-statistics-on-per-client-basis/27640/8

**Comment by yubiuser** [comment]
This should/could be the missing code

**// Advance in steps of interval
			for($i = $from; $i < $until; $i += $interval) {
				if(!array_key_exists($i, $data))
					$data[$i] = 0;
			}`**

from line 397 
https://github.com/pi-hole/AdminLTE/commit/7c4dee6f2d2bbaf57adab317c5c05398537be982#diff-ca74b2e279489420e52e4b2837dc3cbdR397

**Comment by DL6ER** [comment]
Today I finally got a chance to look a this. Good news: You were mostly correct. This code was removed because it had unintended side-effects (it introduced zeros in the data where there should be none). However, when taking into account that the first data point returned by SQLite may not be aligned to your request, it actually works.

---

Current version (note the larger boxes where there were no data in between):
![Screenshot from 2020-04-24 09-47-39](https://user-images.githubusercontent.com/16748619/80188088-fa96b180-8610-11ea-9357-d8f4163d4654.png)

With the code we removed earlier and you suggested for re-adding (note the very thin boxes caused by unaligned (incorrect) zero intervals between all the data points, however, the too wide intervals are fixed):
![Screenshot from 2020-04-24 09-48-01](https://user-images.githubusercontent.com/16748619/80188399-6416c000-8611-11ea-91c7-bdecc61c45a8.png)

When aligning the intervals to the database results, we get the correct result:
![Screenshot from 2020-04-24 09-48-14](https://user-images.githubusercontent.com/16748619/80188709-d8516380-8611-11ea-9ba5-772cab3322af.png)

---

In addition, this also fixes the start and end points, see:

Before (requested was 00:00 - 23:59, returned was only the time the Pi-hole was running yesterday, which was 06:56 - 23:40):
![Screenshot from 2020-04-24 10-01-49](https://user-images.githubusercontent.com/16748619/80189403-e6ec4a80-8612-11ea-9dff-430c4b2a698c.png)

After (shown what was requested):
![Screenshot from 2020-04-24 09-57-33](https://user-images.githubusercontent.com/16748619/80189439-f370a300-8612-11ea-9fd4-a30f1c9fe59e.png)

Please try whether this indeed fixes all the issue you've seen:
```
pihole checkout web fix/long_term_interval_filling
```

**Comment by yubiuser** [comment]
Looks great.
