### ISSUE TITLE
Samesite cookies

### ISSUE THREAD

**Issue by XhmikosR** [pi-hole/AdminLTE#1256]
Currently we have the following console warnings:

```
Some cookies are misusing the recommended “sameSite“ attribute
```

https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

Even though Chrome temporarily reverted the change due to the pandemic, we should really sort this out ASAP.

**Comment by XhmikosR** [comment]
I had a look at this and [made a patch](https://github.com/pi-hole/AdminLTE/compare/devel...cookies), but I have some questions:

1. What are the supported PHP versions? If < 7.3 is supported, my patch needs to be adapted. We should probably add a function and call it everywhere.
2. ~~I'm not sure the way we currently clear the `persistentlogin` cookie is enough; we need to confirm this and maybe setting the expiry date in the past is better~~ This was fixed in #1350 
3. We should probably revisit the cookies `path`; we are not setting it and I'm not sure if it's correct.
4. There's still a `PHPSESSID` cookie which I'm unsure how to tackle
5. We should eventually look into adding the `Secure` option if one is running the admin interface on https
6. Ideally we shouldn't touch the cookie in JS and thus add the `httponly` flag too

**Comment by PromoFaux** [comment]
Sorry, I'll try and answer some questions!

`1.` `PHP` supported version will eventually be 5.3, as we plan to move to an embedded webserver in `FTL` using the (confusingly named) [ph7](https://github.com/symisc/PH7) library, which is based on 5.3


`4.` What is the issue with this cookie? Do we need to do something to it?



`5. `I guess the issue here is that `Secure` only works on `https`, and by default the interface is served via `http`, what is the effect of adding the `Secure` and using it on a `http` site?

**Comment by XhmikosR** [comment]
1. Then someone will need to update my patch, or write a new one so that things work everywhere :)
2. This was fixed
3 and 4 are not fixed
5 and 6: we can't use https blindly; it needs to be set only when we have a https connection otherwise cookies won't work at all on http.

**Comment by PromoFaux** [comment]
Ugh, github took my non sequential list and changed the numbers. (I've edited to force the right numbers, 2 and 3 were supposed to be 4 and 5!) 

RE:5/6 is that something that will need to be done in the PHP side?
