### ISSUE TITLE
"Queries Blocked" and "Percent Blocked" tiles on unauthenticated admin dashboard empty on iOS Safari iPhone/iPad

### ISSUE THREAD

**Issue by DavidAnson** [pi-hole/AdminLTE#1295]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

0

---
**Expected behaviour:**

"Queries Blocked" and "Percent Blocked" tiles on unauthenticated admin dashboard should show numbers on iOS Safari iPhone/iPad just like "Total queries" and "Domains on Blocklist" do

**Actual behaviour:**

Both panels are empty

**Steps to reproduce:**

Load admin page on iOS Safari (13.4.1, latest)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

Tried Chromium on Raspberry Pi and all 4 tiles show values as expected.

**Comment by DavidAnson** [comment]
![C395C0C1-2510-4714-A1D1-47E6D22479D1](https://user-images.githubusercontent.com/1828270/82014161-e56ddb00-9630-11ea-9fca-2b22964483e5.jpeg)

**Comment by PromoFaux** [comment]
Does safari have some kind of element blocking built in?

May sound silly, but those two element IDs begin with `ads_`, and it has been known....

https://discourse.pi-hole.net/t/empty-values-for-queries-and-percentage-blocked-in-the-dashboard/32457

**Comment by DavidAnson** [comment]
Good call! Disabling the 1Blocker content filter for the site shows the content as expected. Any chance you might change the prefix since this sounds like it’s not the first time?

**Comment by PromoFaux** [comment]
This is the second time I've heard it in as many days, so I wonder if it is a new rule added by 1Blocker.

I don't necessarily see why not, though from a quick glance it's not just as straightforward as changing the element names, as nice as that would be, as the elements are named after the properties in the API... and obviously changing those would break any user's scripts that leverage the API

That said : Since drafting this reply I've made a proposal. We shall see what the others say https://github.com/pi-hole/AdminLTE/pull/1296

**Comment by DavidAnson** [comment]
Cool, thanks!

**Comment by pvantilb** [comment]
Not sure if this is related, but on Safari Version 13.1.1 (15609.2.9.1.2 - Catalina OS 10.15.5) with NO adblocker extensions or otherwise, I am seeing the queries blocked and percent blocked on the unauthenticated homepage. Addditionally, after logging in, the "Client activity over last 24 hours", "Query Types", and "Queries Answered By" graphs do not populate and just spin, several JS errors are reported in console window.

Alternatively, Firefox on the same machine (version 79.0 64-bit) works just as expected.

running Pi-hole v5.1.2  Web Interface v5.1.1  FTL v5.2

![pihole_adminlte_safari_bug](https://user-images.githubusercontent.com/22970286/90038615-9e28d200-dc93-11ea-9f2d-9acaf9c36dbf.png)

**Comment by yubiuser** [comment]
This has been fixed a long time ago.
