### ISSUE TITLE
Temperature display changes depending on which page you choose

### ISSUE THREAD

**Issue by JohnM6345789** [pi-hole/AdminLTE#131]
##### Expected Behaviour:
Temperature displayed would be consistent between pages within a small margin of change.

##### Actual Behaviour:
Temperature displayed fluctuates between pages selected, i.e. 
http://ip_address/admin/index.php = 50.38 degrees
http://ip_address/admin/queries.php = 47.61 degrees
http://ip_address/admin/list.php?l=white = 46.0 degrees
http://ip_address/admin/list.php?l=black = 45.54 degrees

If you go from a high temperature page and select another page the temperature can be 5 degrees lower that doesn't seem like it would be possible, the opposite is also true.

##### Steps to reproduce this issue:
Select the different pages and observe the temperature indicator.

**Comment by PromoFaux** [comment]
The temperature is read on each [page load from a system call](https://github.com/pi-hole/AdminLTE/blob/master/header.php#L1-L5), which will fluctuate, and obviously increase under load.

index.php and queries.php are quite load intensive pages, so that would explain the higher temperatures at that point.

**Comment by JohnM6345789** [comment]
But would the temperature decrease as quickly as it shows from page to
page?  I can see the temperature increase but for it to decrease by degrees
doesn't seem right to me. Especially in just a few seconds.

**Comment by PromoFaux** [comment]
In my experience, drops are pretty quick too. 

You can test this yourself on your PC! Run [HWMonitor](http://www.cpuid.com/softwares/hwmonitor.html) to view your CPU temperatures, and then [Prime95](http://www.mersenne.org/download/) to put your CPU under load. Watch what happens when you stop Prime95, you should see the CPU temps drop quite rapidly.

**Comment by dschaper** [comment]
https://github.com/MilhouseVH/bcmstat is a great utility to show realtime in the console what is going on, try that and see if it matches what you are seeing on the web interface.

**Comment by dschaper** [comment]
And yeah @PromoFaux, once you drop the thermal load then if you have heatsinks then it radiates off rather quickly.

**Comment by PromoFaux** [comment]
Closing as not necessarily software related
