### ISSUE TITLE
Enable user to configure forwarding servers

### ISSUE THREAD

**Issue by colindean** [pi-hole/AdminLTE#133]
As raised in pi-hole/pi-hole#643, I would like the ability to configure a forwarding server for certain domains. I see this most commonly being used to forward requests to another internal DNS server, such as one running on an intranet's router, which resolves local LAN domains.

See pi-hole/pi-hole#643 for more information.

@Mcat12 indicated also in [this comment](https://github.com/pi-hole/pi-hole/issues/643#issuecomment-244632466) that this functionality might be implemented in the command line tool primarily, as it's largely a one-time setup task. I can see it being used administratively to add forwarding servers for other, non-standard TLDs like `.bit`.
##

**Comment by diginc** [comment]
Not a bad idea but from a practicality standpoint I'd prefer a 'configure _additional_ dnsmasq options' text editor (_additional_ meaning on top of pi-holes required ones) in the admin interface similar to how WRT routers do it.  Otherwise it is a very slippery slope they'd head down towards supporting [every single dnsmasq option](http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html) in the web interface and worrying about incompatibility of options.

**Comment by DL6ER** [comment]
This is currently out of scope.
