### ISSUE TITLE
request: temperature in Chart

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/AdminLTE#138]
@TylonHH commented on [Mon Sep 12 2016](https://github.com/pi-hole/pi-hole/issues/677)

Hi,
I guess it would be intersting a Chart for the showing CPU Temperature. It has just to be added to the existing "Queries over time" chart.

Like this:
![image](https://cloud.githubusercontent.com/assets/18073299/18435638/bdd1a6a6-78f4-11e6-8df7-286acef259e2.png)
##

**Comment by DL6ER** [comment]
I can work on this as I want to . However, I would have to know some more details: Are we already saving the temperature somewhere (guess not)?

I could imagine the following:

1. Adding a cron job during installation that saves the temperature once a minute (or so) to a list. Is there a place that we'd prefer instead of a cron job? Can cron be expected to be always present?
2. Evaluate the list an show it together with the "Queries over time" graph.

**Comment by DL6ER** [comment]
I came up with something "half working". The problem is that we use ChartJS 1.0.1 while for a second y axis we'd need at least v2.0. However, just updating ChartJS the charts are not rendered anymore.
I'll look further into this issue when I find the time.

![temp](https://cloud.githubusercontent.com/assets/16748619/20003799/afccefe4-a288-11e6-8963-95becb35904e.png)

**Comment by DL6ER** [comment]
I have this now fully implemented:
![untitled1234](https://cloud.githubusercontent.com/assets/16748619/20211244/e8e576b4-a7fd-11e6-8d15-3d314e46d793.png)

Currently, it requires the user to set up a (very simple) small cron job that saves the current temperature every minute. However, I think, this feature is pretty useless without the implementation of my PR #191 which will automatically also increase the resolution of the temperature display.

Having said this, I'm not very sure how we could benefit significantly from having this feature since the temperature of my Pi seems to be rather constant, active usage of the DNS server does not seem to have a noticeable impact.

**Comment by DL6ER** [comment]
Result combined with the code of PR #191:
![screenshot at 2016-11-11 11-21-39](https://cloud.githubusercontent.com/assets/16748619/20211961/1ae908f8-a801-11e6-8894-2d0045b82f6d.png)

**Comment by DL6ER** [comment]
Some more data later on the same day
![screenshot at 2016-11-11 16-20-00](https://cloud.githubusercontent.com/assets/16748619/20219676/ca34b4dc-a82a-11e6-890f-d9c0111fabde.png)

**Comment by dschaper** [comment]
Can we adjust the granularity of the temperature reporting? That graph makes it look a lot worse than it is, 3.5 Celcius delta isn't much at all. And it shows that there actually was a dip in temp during a spike, not relly sure how useful collecting and reporting this is. Scope creep comes in to play if we start adding in features unrelated to DNS activity.

**Comment by TylonHH** [comment]
For me, it looks awesome. I really looking forward to that new information.
Maybe you should make this optional for the user and disable it by default to avoid gossip.

**Comment by dschaper** [comment]
It's interesting information, but it's not advertisement blocking related. We get in to scope creep, do we add disk and ram utilization? If it was a count of unique client IP addresses over time, then I'd be for it, as that is something that we already collect and tells you more about what the Pi-hole is doing. (Is there a single client throwing a ton of queries, does it need to be checked for problems?) But temperature really isn't related to DNS activity as the last graph shows.

**Comment by DL6ER** [comment]
I invested only a few minutes today to see how such a thing would look like. Currently, we have to have the same temporal resolution for all of the displayed data. That is, either values averaged over 1h or over 10min. The dip is related to me having opened the window for a few minutes which ich close to the Raspberry.

@dschaper I fully agree. I expected the temperature to be more influenced by the DNS query rate. However, the experiment showed that the fact that I was in the room had much more influence on the temperature than the load on the Pi himself. Therefore, I'd rather not include it.

@TylonHH
The code I used is publicly available [here](https://github.com/DL6ER/AdminLTE/tree/temperaturedisplay) and I invite everybody to play with it. Nevertheless, I don't intent to open a pull request anymore.

**Comment by dschaper** [comment]
@DL6ER Thanks for the work, and what you've seen in regards to temps on the Pi is similar to my experience. If it's not cased, then airflow will swing it one way or another. And with the temp range the SoC is rated for, (somwhere below 0 and up to 80) it's just something that other packages are better suited at monitoring.

@TylonHH If you're interested in metrics for the pi, there is a package called the RPiMonitor that is on GitHub that has more than we could ever provide, and I think you'll find it to be fitting for what you are looking for.

**Comment by DL6ER** [comment]
Close, as we will most likely never include this.
