### ISSUE TITLE
[Feature Request] Add NTP Option for dhcp in pihole webinterface

### ISSUE THREAD

**Issue by DanielOberlechner** [pi-hole/AdminLTE#2073]
This is a... 

- [X] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

I would like to have the option in pihole webinterface to add the dhcp ntp option.
Dnsmasq has the option to pass a IP which acts as NTP Server. In the pihole webinterface I can't set this. I would have to edit the dnsmasq dhcp config manually and after an update it would be gone.
## Possible Fix
Add a option to enter an IP address which acts as NTP server.

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1.
2. 
3. 
4. 

## Debug steps I have tried

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Odroid C2 with ArchLinux installed
* Docker Version: newest version
* Hardware architecture:

**Comment by DL6ER** [comment]
> I would have to edit the dnsmasq dhcp config manually and after an update it would be gone.

Yes and No. Just create a dedicated file in `/etc/dnsmasq.d/` and it will survive updates. We only rewrite those files that specifically state this in the header.

Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net), as mentioned in our [Issue Templates](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md).

Thank you for your understanding.

**Comment by yubiuser** [comment]
https://discourse.pi-hole.net/t/additional-ntp-server-ui-option-for-dhcp-settings/26233
