### ISSUE TITLE
Landing page shows default lighthttpd page

### ISSUE THREAD

**Issue by VennGrayDog** [pi-hole/AdminLTE#2531]
### Versions

 Pi-hole version is v5.15.5 (Latest: v5.15.5)
  AdminLTE version is v5.18.4 (Latest: v5.18.4)
  FTL version is v5.21 (Latest: v5.21)
  Container tag is: 2023.02.1

### Platform

- OS and version:  Ubuntu 22.04

- Platform:  Docker

### Expected behavior

~~Landing page of PiHole shows a page that asks if I want to go to admin page.~~
http://[IPaddress:port] should show me an error page according to https://pi-hole.net/blog/2023/01/15/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/ (thanks rdwebdesign)

### Actual behavior / bug

Landing page is default Lighttpd page

### Steps to reproduce

1. Go to http://IP:port
4. See wrong landing page

[✓] Your debug token is: https://tricorder.pi-hole.net/wim5hft4rq

### Screenshots

![image](https://user-images.githubusercontent.com/483837/219097188-3d2ffa28-55bb-44e3-9049-a6390c758754.png)

**Comment by VennGrayDog** [comment]
'''
This means that if you browse to your Pi-hole device using just the IP address, you will receive a 403 or 404 error, as there is nothing there to intercept your request.
'''


This is not what I see. I see default lighthttpd page.

**Comment by VennGrayDog** [comment]
According you the link that you provided above when I go to `http://[IP address]` I should receive and error:
```
This means that if you browse to your Pi-hole device using just the IP address, you will receive a 403 or 404 error, as there is nothing there to intercept your request.
```
This is not what I see. 
My initial misunderstanding was that PiHole should be showing landing page.
But now it looks like PiHole should we showing error page and instead I am getting default lighttpd page - which is also wrong.

**Comment by rdwebdesign** [comment]
The text was written for bare metal installs in mind. Inside a docker container the behavior I posted is the correct one.

> But now it looks like PiHole should we showing error page and instead I am getting default lighttpd page - which is also wrong.

No. 
There is no **error page**, only an error message and your browser will show the error for you.
(the text says: **"you will receive a 403 or 404 error"**, but again: this is on bare metal installs) 

Inside the container, there is a config to avoid the error. That's why you see this page even using an IP.

You can also set the `FTLCONF_LOCAL_IPV4=<your_pihole_IP>`. This will avoid the page and you don't need to type `/admin`.

**Comment by rdwebdesign** [comment]
You are not reading:

Add `/admin`.

Use `http://192.168.0.50:8280/admin`

**Comment by VennGrayDog** [comment]
I am reading :-) I understand how to reach admin page. I understand that I need to add `/admin`.
My issue is not with admin page, but with `http://[ip:port]` page.
This is page that is serviced by the same lighttpd server as admin page. 
According to release notes linked above this page should from now on return 404 error code to the browser.
Instead lighttpd returns "default" page.
This is the issue that needs to be fixed.

**Comment by dschaper** [comment]
Then remove the `index.html` file from `/var/www/html`. We don't include that file so we don't expect it to be there. 

The changes made and referenced in the release notes are for you to be able to set up what ever services you'd like to see or use at `http://IP` instead of being forced to see Pi-hole there. So now you can, just happens that your setup put the default `lighttpd` page there. 

No issue here really.

**Comment by VennGrayDog** [comment]
I am using official Pi-Hole docker container. And I `--force-recreate`d it before posting this question. Any `index.html` that is present comes from official pi-hole docker image.

**Comment by dschaper** [comment]
Okay, what I see from the official Pi-hole docker image:

`/etc/lighttpd/lighttpd.conf` shows 

`index-file.names            = ( "index.php", "index.html" )`

You should be able to confirm the same on yours. Then taking a look at the contents of the `/var/www/html` directory:
```plain
root@6688743fd3b1:/etc/lighttpd/conf-enabled# cd /var/www/html
root@6688743fd3b1:/var/www/html# ls
admin  index.lighttpd.html
```

There isn't an `index.html` file there. Since you are using Docker can you please provide the docker-compose or the docker run command you are using? Also the debug token URL you provided does not exist, can you run the debug again and provide a new token?

**Comment by VennGrayDog** [comment]
```
root@ea4933c6eaac:/# cat /etc/lighttpd/lighttpd.conf |grep index-file
index-file.names            = ( "index.php", "index.html" )
```
```
root@ea4933c6eaac:/# ls -la /var/www/html
total 16
drwxrwxr-x 1 www-data www-data 4096 Feb 12 11:09 .
drwxr-xr-x 1 root     root     4096 Feb 11 21:04 ..
drwxr-xr-x 7 root     root     4096 Feb 12 11:09 admin
-rw-r--r-- 1 root     root     3388 Feb 11 21:05 index.lighttpd.html
```
```
pihole:
        image: pihole/pihole:latest
        container_name: pihole
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "8280:80/tcp"
        environment:
            - TZ=America/Toronto
        volumes:
            - './etc:/etc/pihole'
            - './dnsmasq.d:/etc/dnsmasq.d'    
        restart: unless-stopped
```

**Comment by VennGrayDog** [comment]
after 
```
root@ea4933c6eaac:/var/www/html# mv index.lighttpd.html index.lighttpd.html.old
```
Now I get correct behavior:
![image](https://user-images.githubusercontent.com/483837/219132965-e7bc1a5b-3a3e-42d0-91e7-ba275c1381f4.png)

**Comment by dschaper** [comment]
Okay, can you explain why you see that as 'correct' behavior? Is that because you want a 403 or because the documentation says 403? 

What is it that you want to happen?
