### ISSUE TITLE
Possible Issue - No Option to Update List

### ISSUE THREAD

**Issue by slamanna212** [pi-hole/AdminLTE#31]
I just installed Pi Hole and love it. I used the install script on a fresh install of debian. The only issue is , i dont have the option to update the lists, is that not live yet?

**Comment by dschaper** [comment]
The lists are updated when you first install the program and are updated everytime `gravity.sh` is run. There is a `cron` script to update the lists, and if you ever need to blacklist or whitelist a site, then those scripts will also trigger a `gravity.sh` run. So if you'd like to do a manual update, just run `gravity.sh` from a command prompt!

**Comment by slamanna212** [comment]
Oh wow, thanks for the lightning quick response! Quick question, i checked
for crons using crontab -e for the pi user but didnt see any, are they run
as a different user and what is the frequency?

**Comment by dschaper** [comment]
The cron file is at https://github.com/pi-hole/pi-hole/blob/master/advanced/pihole.cron and the install should drop that file in `/etc/cron.d/pihole`

**Comment by dschaper** [comment]
It does currently require sudo capability because it needs to reload/restart `dnsmasq` but we are working on that and have a few options that we are trying so we can see what runs the best on the most installs. We're security conscious with our users installs and respect the trust you all give us so we want to make sure we are doing the most we can with the least amount of privileged/elevated commands.
