### ISSUE TITLE
switching servers

### ISSUE THREAD

**Issue by soydepr** [pi-hole/AdminLTE#848]
*i want to switch lighttpd to nginx
where is this specified in pi-hole 

 [✓] Starting lighttpd service
  [✓] Enabling lighttpd service to start on reboot

**Comment by Mcat12** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Nginx is not a supported web server.
