### ISSUE TITLE
uBlock Origin blocks some of the UI

### ISSUE THREAD

**Issue by Random90** [pi-hole/AdminLTE#850]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`7`

---
**Expected behaviour:**

`Proper display of statistics on the index page`

**Actual behaviour:**

`Queries Blocked and Percent Blocked don't display properly.`
![obraz](https://user-images.githubusercontent.com/13310754/46233379-9fd49f80-c372-11e8-863a-99bb9887d524.png)

**Steps to reproduce:**

`Just view main page with uBlock origin enabled`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`No need`

**Troubleshooting undertaken, and/or other relevant information:**

The problem is a part of uBlock origin cosmetic blocking filter: '[id^="ads_"]'
Changing id of 
`
<span id="ads_blocked_today" class="">---</span>
` and 
`
<span id="ads_percentage_today" class="">---</span> 
` 
to something else would fix issue for any uBlockOrigin users.
I know I can fix it just by turning uBlock Origin off, but it took quite some time for me to realize that is not a pihole UI problem.

**Comment by rrobgill** [comment]
Instead of disabling ublock origin entirely, you can [disable cosmetic filtering on a per-site basis](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering), and just disable it on your pi-hole.

This is not a bug with pi-hole, or ublock origin, but as you have pointed out, an overzealous filter entry from one or more filter lists. (It may be good if you could report the false positive to the maintainer of the filter list that contains it, they may be able to add a whitelist entry to work around it).

**Comment by Random90** [comment]
> It may be good if you could report the false positive to the maintainer of the filter list that contains it, they may be able to add a whitelist entry to work around it
You are right, sorry for bothering
