### ISSUE TITLE
DHCP: defining other options

### ISSUE THREAD

**Issue by trendchiller** [pi-hole/AdminLTE#877]
It would be great if you could make it possible to define own DHCP options ans parameters.

**Comment by Mcat12** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net), as mentioned in our [Issue Templates](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md).

Thank you for your understanding.
