### ISSUE TITLE
Queryads broken when using nginx reverse proxy

### ISSUE THREAD

**Issue by rawr0r** [pi-hole/AdminLTE#925]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**
query the ads list.

**Actual behaviour:**
404 - /admin/scripts/pi-hole/php/queryads.php

**Steps to reproduce:**
use a reverse proxy which links directly to the /admin/ dir

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

since it works just fine with the rest of the web panel, this should be adressed for consistency:

queryads.js

line 77
        httpGet(ta,quiet,"/admin/scripts/pi-hole/php/queryads.php?domain="+domain.toLowerCase()+exact+"&IE"); 

line 82
	 var source = new EventSource("/admin/scripts/pi-hole/php/queryads.php?domain="+domain.toLowerCase()+"&"+exact);

remove the "/admin/" from the url.

**Comment by Mcat12** [comment]
Nginx is not a supported configuration, and we can't support arbitrary mount points with this web interface (this would be easily handled in the upcoming web interface, however).

If we removed `/admin/` from the URL, then it would break everyone else's install.

**Comment by rawr0r** [comment]
I guess youre right. heres a workaround jsut in case someone needs it:

`
	location /admin/ {
		rewrite ^/admin(.*) /$1 permanent;
	}
`

**Comment by sudo-bmitch** [comment]
I'm also seeing this issue, this time with traefik as a reverse proxy for Pi-Hole running inside of a docker container. Any path based reverse proxy is doing this because the queryads.js as an absolute rather than relative path. Changing the request to a relative path makes the script work as expected. I'm curious of the scenarios where a relative path breaks other user environments, seems like support for environments where relative paths break would be even further out of scope.

For other docker users, the fix make "Find Blocked Domain In Lists" work behind a path based proxy is to create the following script called fix-queryads.sh:

```
#!/bin/sh
sed -i 's@/admin/@@' /var/www/html/admin/scripts/pi-hole/js/queryads.js
```

And then a Dockerfile:

```
FROM pihole/pihole:latest
COPY fix-queryads.sh /etc/cont-init.d/90-fix-queryads.sh
```

Then build and run that image. Or you could mount that script as a volume.

**Comment by sudo-bmitch** [comment]
This was fixed in https://github.com/pi-hole/AdminLTE/pull/1046
