### ISSUE TITLE
Host dashboard on githubpages (or not on the same machine)

### ISSUE THREAD

**Issue by Macley-Kun** [pi-hole/AdminLTE#927]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behaviour:**

`I would like to know if it's possible to host the dasbhoard on a different machine, maybe even github pages?`

**Actual behaviour:**

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{I've looked at the source code, hoping to find a config variable somewhere to fix the issue myself.}`

Also if it's not possible at this point, i will close this ASAP and request a feature here!
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.

Thank you for reading, love the Pi-Hole project!

**Comment by Mcat12** [comment]
This is impossible because this web interface uses PHP. GitHub Pages only serves static files.

The new upcoming web interface separates the web interface from the API, so it can be hosted statically. See https://web.pi-hole.io for a preview (hosted on GitHub Pages). If you want it to connect to an API on a different machine, you will have to compile it with a different API endpoint yourself. It assumes that the API is mounted on the same host.
