### ISSUE TITLE
Query Log: Wrong sort order (equal timestamp)

### ISSUE THREAD

**Issue by ghost** [pi-hole/AdminLTE#934]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`"Query Log" ("Recent Queries") in the "Pi-hole Admin Console" should show the recent queries in correct sort order.`

**Actual behaviour:**

`The sort order is not correct (or may not be correct) for log entries with the same timestamp.
Especially if you have blocked and non-blocked queries at the same time it's confusing to have the blocked entries (in time) before the non-blocked entries.`

**Steps to reproduce:**

`Do DNS requests and check the result in the Admin Console ("Query Log" / "Recent Queries") and also in the log-file and/or in the database.`
Note: There must be several DNS requests at the same timestamp (the same second).
N.B.: The default sort order for "Recent Queries" is descending by time.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`f2o6gv35po`

**Troubleshooting undertaken, and/or other relevant information:**

- (checked source code).

Note: I saw this wrong sort order also often in the past.

The "problem" is because of just using UNIX timestamps in the log and database.   
UNIX timestamps only have seconds and so they are not very accurate (no fractions of a second, i.e. no milliseconds/nanoseconds).

The query seems to use the timestamp as only sort-criteria.
https://github.com/pi-hole/AdminLTE/blob/f2b2aa42c0b37ab16ada30f0162a14782a82807c/api_db.php#L104 
https://github.com/pi-hole/AdminLTE/blob/f2b2aa42c0b37ab16ada30f0162a14782a82807c/api_db.php#L122

The result for the website will be re-sorted by .js:
https://github.com/pi-hole/AdminLTE/blob/347994db169eb486954cbcff6f62955c77c1db4a/scripts/pi-hole/js/queries.js#L293

[I'm not skilled with web-applications and I hope I've linked to relevant source code.]

---

Let's look to an _example_, to see it more clearly.

In the web interface (with default sort order: descending by time) the _blocked_ entries (`www.akamai.net`) seems to be before the _forwarded_ entries (`akamai.net`).  All entries have the same timestamp ("23:58:08").
![Pi-hole - Wrong sort order (Web interface)](https://user-images.githubusercontent.com/44007403/56871851-c222be80-6a22-11e9-8f01-44417416fc94.png)

In the log file you can see the truth: The forwarded entries are before the blocking entries.
```
# cat /var/log/pihole.log.1 | grep 23:58:0
Apr 28 23:58:08 dnsmasq[719]: query[A] akamai.net from 192.168.1.10
Apr 28 23:58:08 dnsmasq[719]: forwarded akamai.net to 127.0.0.1
Apr 28 23:58:08 dnsmasq[719]: query[A] akamai.net from 192.168.1.10
Apr 28 23:58:08 dnsmasq[719]: forwarded akamai.net to 127.0.0.1
Apr 28 23:58:08 dnsmasq[719]: reply akamai.net is NODATA-IPv4
Apr 28 23:58:08 dnsmasq[719]: query[A] www.akamai.net from 192.168.1.10
Apr 28 23:58:08 dnsmasq[719]: /etc/pihole/regex.list www.akamai.net is 0.0.0.0
Apr 28 23:58:08 dnsmasq[719]: query[A] www.akamai.net from 192.168.1.10
Apr 28 23:58:08 dnsmasq[719]: /etc/pihole/regex.list www.akamai.net is 0.0.0.0
```

Also in the database I can see the _forwarded_ `akamai.net` entries before the _blocked_ `www.akamai.net` entries.
```
sqlite> select * from queries where timestamp = 1556488688 and domain like '%akamai%';
127217|1556488688|1|2|akamai.net|192.168.1.10|127.0.0.1
127218|1556488688|1|2|akamai.net|192.168.1.10|127.0.0.1
127219|1556488688|1|4|www.akamai.net|192.168.1.10|
127220|1556488688|1|4|www.akamai.net|192.168.1.10|
```

---

Possible solutions:
* Use a more precise timestamp.
* Select also the `id` from the database table, pass it thru the API/.js/.php and use the `id` for sorting (only internally/in the background/hidden; it might not be useful to display the `id` on the web-site).

**Comment by Mcat12** [comment]
Thanks for the in-depth review of the issue! Note that there's two cases here which need to be handled.
1. When the query data comes from FTL (in-memory)
2. When the query data comes from the database (long term data)

The in-memory queries can also contain queries from the database, as FTL pulls the last 24 hours of queries when starting up.

**In-memory**
You linked the database queries for case 2, but the query log only pulls data from the in-memory store (case 1). The API (technically FTL) does correctly order the queries when it sends them to the web interface, but as you found the table sorts them again. Since the user is then allowed to resort the data, we can't rely on the order given by the API. Probably, we would want to also pass through the ID.

**Database**
In the database case, things are similar because it uses the same table, so the backend order doesn't matter much. The ID should probably be passed through as well.

**Solution**
I'm not sure if we should solve this issue in this web interface, as we are going to replace it with a new web interface and API which does not have this issue. Any work done on this web interface will be lost.

The new web interface uses server-side pagination and filtering for the query log. It also combines the in-memory and database query logs into one continuous log. Code:
http://github.com/pi-hole/web
http://github.com/pi-hole/api

As I mentioned above, this web interface does not have this sorting issue. It handles this case correctly because it uses the order that the API returns, and does not allow the user to re-sort the queries. The API sorts by ID in both in-memory and DB cases.

In the future if we add sorting back, it would happen on the server-side and therefore the web interface will still use the API's order, so the issue will not reappear.

**Comment by DL6ER** [comment]
> Probably, we would want to also pass through the ID

This would lead to an overhead in transmitted data, even though this might be acceptable (few bytes per query). However, we could even work without transmitting the ID as you mentioned that

> The API (technically FTL) does correctly order the queries when it sends them to the web interface

so we can implicitly add the ID in the receiving JavaScript when adding the data to the table. This has the benefit that the socket format does not need to be changed. I haven't worked all that much with DataTables for almost a year, is it possible to add a hidden field (such as this new ID) which is used by the table to sort by as a secondary field (to give a hint for the correct sorting if there is the issue of two identical timestamps)?

**Comment by DL6ER** [comment]
Further investigations reveal that this is an issue with how the sorting in DataTables works. We transmit the data in the form: `oldest (first) to newest (last)` but display them as `newest (first) to oldest (last)`.

This can be confirmed when adding the ID of the AJAX element as additional row.

1. Regular displaying with `oldest (first) to newest (last)`, screenshot of the **last** table page
![Screenshot from 2019-05-05 13-10-58](https://user-images.githubusercontent.com/16748619/57193082-cd507f80-6f37-11e9-9536-907660228d24.png)
You can see that the IDs are still descending for each equal timestamp. They should actually be ascending here for the expected display!

2. If we reverse the sorting (show oldest first) and look at the first table page, everything is well ordered:
![Screenshot from 2019-05-05 13-11-19](https://user-images.githubusercontent.com/16748619/57193104-025cd200-6f38-11e9-9d87-e0cd40e5eb1d.png)

Question is now what should be done, I see basically three possibilities:
1. Reverse the order in which FTL is returning out the queries, i.e., invert the direction in which the loop runs (`i--` instead of `i++`). Would this break anything? I'm afraid it might break user scripts.
2. Define this field as (hidden) secondary sorting field. A slight issue is that we need to invert sorting on this column as well if the user inverts the sorting on the timestamp field to stay consistent. I'm not yet sure how much hacking into the DataTable's code this might mean.
3. Add a fractional part to the timestamp (like `1234.0001`, `1234.0002`, ...) and cut this fractional part before we create the displayed timestamp string.

I'm in favor of option three as it will allow the expected behavior (it makes the timestamps non-equal!) whilst not changing anything else.

**Comment by Mcat12** [comment]
If we add a separate ID column either in the PHP or JS code, we can more easily sort it using https://stackoverflow.com/a/43317014. Then we would avoid modifying the actual data.

That being said, all of this work will be lost when we switch to the new web interface, so we have to decide if it is worth it.
