### ISSUE TITLE
API blocked Domains malforms Dashboard statistic

### ISSUE THREAD

**Issue by Vepox** [pi-hole/AdminLTE#958]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

If I add a Top Domain in API settings I do not want it to be added in the statistic

**Actual behaviour:**

Top Domain is just hidden, but not removed from statistic

**Steps to reproduce:**

Add a highly visited Top Domain

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

f3j5wiy6v8

![Graphical Representaion of the Bug](https://user-images.githubusercontent.com/15816910/58994313-5b967a80-87f0-11e9-9763-4504dddfcca6.png)

**Comment by Mcat12** [comment]
You are bringing up two separate issues, is that right?
1. Blocked queries are not shown as blocked in the query graph
2. The scale is not adjusted when a domain is removed from the top lists

The first issue requires more information. What tells you that the queries in that time range are blocked?

The second is intentional. The frequency of the domains is how often they appear out of all of the relevant requests. In the case of Top Blocked Domains, the number of requests is how many blocked queries there were. In order to retain an accurate measurement of how often the domain is seen, we still count domains which are hidden from display. It sounds like you want to change this behavior to make it as if Pi-hole has never seen the domain. That is very different than simply hiding it from a specific set of statistics, which is what the feature is currently designed to do.

**Comment by Vepox** [comment]
Reg. 2nd: Ok then this issue is closed I guess

Reg. 1st:
I know this because I only have this one client (Smart TV) pushing out so many DNS resolve requests. Before I had added the Domain (cdn.samsungcloudsolution.com) to the Top Domains API thiny, the statistic looked really, really similar.
And I know for a fact, that the TV stops trying to resolve the Domain, if the TV gets a proper answer. To put it in other words: The ammount of DNS requests would not be as high if they had been been properly answered (so they must've been blocked by pi-hole).

**Comment by Mcat12** [comment]
Have you checked in that time frame that those queries are blocked? Right now your reasoning is based on assumptions and guesses.

**Comment by Vepox** [comment]
I rechecked everyting, but I could'nt reproduce the problem. I put the blame on the gremlins.
